# Solving Systems of Equations

In mathematics, a system of linear equations (or linear system) is a collection of two or more linear equations involving the same set of variables.
* check this: https://en.wikipedia.org/wiki/System_of_linear_equations#Matrix_equation
* https://courses.lumenlearning.com/ivytech-collegealgebra/chapter/solving-a-system-of-linear-equations-using-matrices/

If you have the following system of equations:

$5x + 3y + 9z =  -1$

$-2x + 3y - z =  -2$

$-x - 4y + 5z =  1$

We can express the above equations in the matrix form $A \cdot X =  B$:

$$
\begin{bmatrix} 
5 & 3 & 9\\
-2 & 3 & -1\\
-1 & -4 & 5\\
\end{bmatrix}
\quad
\begin{bmatrix} 
x\\
y\\
z\\
\end{bmatrix}
=
\quad
\begin{bmatrix} 
-1\\
-2\\
1\\
\end{bmatrix}
$$

If the matrix A is square (has nxn dimension), then the system has a unique solution given by:

$A \cdot X =  B$

$ A \cdot  A^{-1} \cdot X = A^{-1}\cdot B$

$ \therefore X = A^{-1} \cdot B$


Create a Python program that will solve a system of `n` linear equations. By using Numpy, solving systems of equations becomes even easier to do!

## Input Specification
1. Ask the user to input the desired number of linear equations (this also equates to the matrix dimension)

```Input dimension: 3 ```

2. Ask the user to input `nxn` numbers separated by comma. This will be the A matrix.

```Enter matrix A: 5, 3, 9, -2, 3, -1, -1, -4, 5 ```

3. Ask the user to input `n` numbers separated by comma. This will be the B matrix.

```Enter matrix B: -1, -2, 1```

## Output Specification
1. Print out the solution to the system of equations:

```The solution is:  0.326, -0.492, -0.128```

## Process
1. Parse inputs `2` and `3`

2. Inverse matrix A 

3. Perform dot multiplication on $A^{-1}$ and $B$ to solve for the solution

4. To practice your skills in Numpy, do not use the `np.linalg.solve` method. We will be using it however to verify if your solution is correct

# !! Important !!
1. Store the coefficient matrix in a Python variable `A` (case sensitive)
2. Store the ordinates or “dependent variables” vector in a Python variable `B` (case sensitive)
3. Store the solution vector in a Python variable `X` (case sensitive)

## Hints:
1. You can use a string's `split(delimeter)` function to split the input
2. Numpy's `reshape()` function is great for converting a numpy array into a numpy matrix
3. Use the last cell on the notebook to test out if your solution is correct.

In [1]:
import numpy as np

## Procedural Solution

In [20]:
# get inputs as string
# straight away convert input to string
dim = int(input('Input dimension:'))
A_str = input('Enter matrix A:')
B_str = input('Enter matrix B:')

# A_str.split(',') outputs a list of strings, np.array accepts list
A = np.array(A_str.split(','))
# numpy function to convert type of numpy array from one type to another. In this case from an array of strings
# to array of floats
A = A.astype('float')
# reshape A from 1 dimenstion to dim x dim matrix
A = A.reshape(dim,dim)

# B_str.split(',') outputs a list of strings, np.array accepts list
B = np.array(B_str.split(','))
# numpy function to convert type of numpy array from one type to another. In this case from an array of strings
# to array of floats
B = B.astype('float')

X = np.linalg.inv(A)@B
print(X)


Input dimension:3
Enter matrix A:5, 3, 9, -2, 3, -1, -1, -4, 5
Enter matrix B:-1,-2,1
[ 0.32620321 -0.49197861 -0.12834225]


## OOP Solution

In [21]:
class SystemOfEquations():
    # we set default values to None so we can accept empty initializations as well as different input types 
    def __init__(self, dim = None, A = None, B = None):
        # this assumes dim if passed is an integer
        if dim is not None:
            self.dim = dim
        else:
            self.dim = None
        # if A was passed, check if it is a numpy array, string or list, then process accordingly
        if A is not None:
            if type(A) == np.ndarray:
                self.A = A
            elif type(A) == str:
                self.A = np.array(A.split(','))
                self.A = self.A.astype('float')
                self.A = self.A.reshape(self.dim, self.dim)
            elif type(A) == list:
                self.A = np.array(A)
                self.A = self.A.astype('float')
                self.A = self.A.reshape(self.dim, self.dim)
        else:
            self.A = None
        
        # if B was passed, check if it is a numpy array, string or list, then process accordingly
        if B is not None:
            if type(B) == np.ndarray:
                self.B = B
            elif type(B) == str:
                self.B = np.array(B.split(','))
                self.B = self.B.astype('float')
            elif type(B) == list:
                self.B = np.array(B)
                self.B = self.B.astype('float')
        else:
            self.B = None
            
        self.X = None
    
    # the implementation of the method is very similar to procedural code
    def getMatrices(self):
        dim = int(input('Input dimension:'))
        A_str = input('Enter matrix A:')
        B_str = input('Enter matrix B:')

        # A_str.split(',') outputs a list of strings, np.array accepts list
        self.A = np.array(A_str.split(','))
        # numpy function to convert type of numpy array from one type to another. In this case from an array of strings
        # to array of floats
        self.A = self.A.astype('float')
        # reshape A from 1 dimenstion to dim x dim matrix
        self.A = self.A.reshape(dim,dim)

        # B_str.split(',') outputs a list of strings, np.array accepts list
        self.B = np.array(B_str.split(','))
        # numpy function to convert type of numpy array from one type to another. In this case from an array of strings
        # to array of floats
        self.B = self.B.astype('float')
        # return a tuple containing A and B
        return self.A, self.B
    
    # solve for X    
    def solve(self):
        self.X = np.linalg.inv(self.A) @ self.B
        
        return self.X
            

## Sample OOP Solution based on Exercise Specs

In [22]:
system_eq = SystemOfEquations()
# I'm catching the values of A and B tuple in one line
A, B = system_eq.getMatrices()
# catch X value
X = system_eq.solve()
# print values
print('A:', A, sep='\n')
print('B:', B, sep='\n')
print('X:', X, sep='\n')

Input dimension:3
Enter matrix A:5, 3, 9, -2, 3, -1, -1, -4, 5
Enter matrix B:-1,-2,1
A:
[[ 5.  3.  9.]
 [-2.  3. -1.]
 [-1. -4.  5.]]
B:
[-1. -2.  1.]
X:
[ 0.32620321 -0.49197861 -0.12834225]


## Sample OOP accepting list input

In [23]:
# list of numbers
A_list = [5, 3, 9, -2, 3, -1, -1, -4, 5]
B_list = [-1,-2,1]
system_eq = SystemOfEquations(3,A_list, B_list)

A = system_eq.A
B = system_eq.B
X = system_eq.solve()

print('A:', A, sep='\n')
print('B:', B, sep='\n')
print('X:', X, sep='\n')

A:
[[ 5.  3.  9.]
 [-2.  3. -1.]
 [-1. -4.  5.]]
B:
[-1. -2.  1.]
X:
[ 0.32620321 -0.49197861 -0.12834225]


## Sample OOP accepting string input

In [24]:
# string input sample
A_str = "5, 3, 9, -2, 3, -1, -1, -4, 5"
B_str = "-1,-2,1"
system_eq = SystemOfEquations(3, A_str, B_str)

A = system_eq.A
B = system_eq.B
X = system_eq.solve()

print('A:', A, sep='\n')
print('B:', B, sep='\n')
print('X:', X, sep='\n')

A:
[[ 5.  3.  9.]
 [-2.  3. -1.]
 [-1. -4.  5.]]
B:
[-1. -2.  1.]
X:
[ 0.32620321 -0.49197861 -0.12834225]


## Sample OOP accepting numpy array

In [25]:
# direct numpy array sample

A = np.array([[5, 3, 9],
              [-2, 3, -1],
              [-1, -4, 5]])
B = np.array([-1,-2,1])
system_eq = SystemOfEquations(3, A, B)
X = system_eq.solve()

print('A:', A, sep='\n')
print('B:', B, sep='\n')
print('X:', X, sep='\n')

A:
[[ 5  3  9]
 [-2  3 -1]
 [-1 -4  5]]
B:
[-1 -2  1]
X:
[ 0.32620321 -0.49197861 -0.12834225]


In [26]:
# Run this to test if your solution is correct. If wrong, this will output an error
assert np.allclose(X,np.linalg.solve(A,B)), "Solution incorrect \n"+str(X)+" \n\n not equal to \n\n "+str(np.linalg.solve(A,B))